# Generated by Django 5.1.6 on 2025-02-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='moveset',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='first_move',
            field=models.ManyToManyField(related_name='first_move', to='duck.move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='fourth_move',
            field=models.ManyToManyField(related_name='fourth_move', to='duck.move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='second_move',
            field=models.ManyToManyField(related_name='second_move', to='duck.move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='third_move',
            field=models.ManyToManyField(related_name='third_move', to='duck.move'),
        ),
        migrations.DeleteModel(
            name='Moveset',
        ),
    ]
