# Generated by Django 5.1.6 on 2025-02-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0002_remove_pokemon_moveset_pokemon_first_move_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='first_move',
            field=models.ManyToManyField(blank=True, related_name='first_move', to='duck.move'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='fourth_move',
            field=models.ManyToManyField(blank=True, related_name='fourth_move', to='duck.move'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='second_move',
            field=models.ManyToManyField(blank=True, related_name='second_move', to='duck.move'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='third_move',
            field=models.ManyToManyField(blank=True, related_name='third_move', to='duck.move'),
        ),
    ]
