# Generated by Django 5.1.6 on 2025-02-12 13:13

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0004_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='first_move',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='second_move',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='first_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_move', to='duck.move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='second_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_move', to='duck.move'),
        ),
    ]
