# Generated by Django 5.1.6 on 2025-02-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0005_remove_pokemon_first_move_remove_pokemon_second_move_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='fourth_move',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='third_move',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='fourth_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_move', to='duck.move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='third_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_move', to='duck.move'),
        ),
    ]
