# Generated by Django 5.1.6 on 2025-02-13 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0006_remove_pokemon_fourth_move_remove_pokemon_third_move_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_type', to='duck.type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_type', to='duck.type'),
        ),
    ]
