# Generated by Django 5.1.6 on 2025-02-17 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0007_move_type_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='not_very_effective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notveryeffective', to='duck.type'),
        ),
        migrations.AddField(
            model_name='type',
            name='super_effective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supereffective', to='duck.type'),
        ),
    ]
