# Generated by Django 5.1.6 on 2025-02-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0009_alter_pokemon_first_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='first_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_move', to='duck.move'),
        ),
    ]
